Nakard\Laboratory\ApplicationBundle\Entity\Tests\Test:
    type: entity
    table: tests
    repositoryClass: Nakard\Laboratory\ApplicationBundle\Entity\Tests\TestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: decimal
        registerDate:
            type: datetime
        conductDate:
            type: datetime
        samples:
            type: array
    lifecycleCallbacks: {  }
    manyToOne:
      patient:
        targetEntity: Nakard\Laboratory\ApplicationBundle\Entity\Users\Patient
        reversedBy: tests
      scheduler:
        targetEntity: Nakard\Laboratory\ApplicationBundle\Entity\Users\Doctor
        reversedBy: schedulesTests
      labAssistant:
        targetEntity: Nakard\Laboratory\ApplicationBundle\Entity\Users\LaboratoryAssistant
        reversedBy: assignedTests
