Nakard\Laboratory\ApplicationBundle\Entity\Users\User:
    type: entity
    table: users
    repositoryClass: Nakard\Laboratory\ApplicationBundle\Entity\Users\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
        length: 255
    discriminatorMap:
        patient: Patient
        assistant: LaboratoryAssistant
        doctor: Doctor
        admin: Administrator
    fields:
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        login:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        pesel:
            type: string
            length: 255
        registerDate:
            type: datetime
    lifecycleCallbacks: {  }
