Nakard\Laboratory\ApplicationBundle\Entity\Users\Patient:
    type: entity
    table: users
    repositoryClass: Nakard\Laboratory\ApplicationBundle\Entity\Users\PatientRepository
    lifecycleCallbacks: {  }
    oneToMany:
      tests:
        targetEntity: Nakard\Laboratory\ApplicationBundle\Entity\Tests\Test
        mappedBy: patient
      samples:
        targetEntity: Nakard\Laboratory\ApplicationBundle\Entity\Tests\Sample
        mappedBy: patient