Nakard\Laboratory\TestBundle\Entity\Tests\Test:
    type: entity
    table: tests
    repositoryClass: Nakard\Laboratory\TestBundle\Entity\Tests\TestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: decimal
            precision: 10
            scale: 2
            nullable: true
        registerDate:
            column: register_date
            type: datetime
        conductDate:
            column: conduct_date
            nullable: true
            type: datetime
    lifecycleCallbacks:
        prePersist: [setUpRegisterDate]
    manyToOne:
        patient:
            targetEntity: Nakard\Laboratory\UserBundle\Entity\Users\Patient
            inversedBy: tests
        scheduler:
            targetEntity: Nakard\Laboratory\UserBundle\Entity\Users\Doctor
            inversedBy: scheduledTests
        labAssistant:
            joinColumn: laboratory_assistant_id
            targetEntity: Nakard\Laboratory\UserBundle\Entity\Users\LaboratoryAssistant
            inversedBy: assignedTests
        testType:
            joinColumn: test_type_id
            targetEntity: Nakard\Laboratory\TestBundle\Entity\Tests\TestType
            inversedBy: tests
    manyToMany:
        samples:
            targetEntity: Nakard\Laboratory\SampleBundle\Entity\Samples\Sample
            inversedBy: tests