Nakard\Laboratory\TestBundle\Entity\Tests\TestType:
    type: entity
    table: test_type
    repositoryClass: Nakard\Laboratory\TestBundle\Entity\Tests\TestTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        createdAt:
            column: created_at
            type: datetime
    lifecycleCallbacks:
        prePersist: [setUpRegisterDate]
    manyToMany:
        packets:
            targetEntity: Nakard\Laboratory\TestBundle\Entity\Tests\TestPacket
            mappedBy: testTypes
    oneToMany:
        tests:
            targetEntity: Nakard\Laboratory\TestBundle\Entity\Tests\Test
            mappedBy: testType
    manyToOne:
        sampleType:
            targetEntity: Nakard\Laboratory\SampleBundle\Entity\Samples\SampleType
            inversedBy: testTypes
            joinColumn:
                name: sample_type_id
                referencedColumnName: id