parameters:
#    nakard_laboratory_sample.example.class: Nakard\Laboratory\SampleBundle\Example
    nakard_laboratory_sample.admition.service.class: Nakard\Laboratory\SampleBundle\Service\SampleAdmitionService

services:
#    nakard_laboratory_sample.example:
#        class: %nakard_laboratory_sample.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    nakard_laboratory_sample.admition_service:
        class: %nakard_laboratory_sample.admition.service.class%
        arguments: [@doctrine]