nakard_laboratory_application_users_index:
    path:     /users/{page}
    defaults: { _controller: NakardLaboratoryUserBundle:User:index, page: 1}
    requirements:
        page: \d+

nakard_laboratory_application_users_add:
    path:     /users/add
    defaults: { _controller: NakardLaboratoryUserBundle:User:add}

nakard_laboratory_application_homepage:
    path:     /{name}
    defaults: { _controller: NakardLaboratoryUserBundle:Default:index, name: 'Stranger' }

nakard_laboratory_application_registration:
    path:     /register/{type}
    defaults: { _controller: NakardLaboratoryUserBundle:Registration:register}
    requirements:
        type: doctor|patient|admin|assistant