nakard_laboratory_application_users_index:
    path:     /users/{page}
    defaults: { _controller: NakardLaboratoryUserBundle:User:index, page: 1}
    requirements:
        page: \d+

nakard_laboratory_application_users_add:
    path:     /add/{type}
    defaults: { _controller: NakardLaboratoryUserBundle:Registration:add, type: ''}
    requirements:
        type: doctor|patient|admin|assistant

nakard_laboratory_application_homepage:
    path:     /
    defaults: { _controller: NakardLaboratoryUserBundle:Default:index }