nakard_laboratory_application_users_index:
    path:     /users/{page}
    defaults: { _controller: NakardLaboratoryUserBundle:User:index, page: 1}
    requirements:
        page: \d+

nakard_laboratory_application_users_add:
    path:     /users/add
    defaults: { _controller: NakardLaboratoryUserBundle:User:add}