parameters:
#    nakard_laboratory_application.example.class: Nakard\Laboratory\UserBundle\Example

services:
#    nakard_laboratory_application.example:
#        class: %nakard_laboratory_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    nakard_laboratory_application.user_resolver:
        class: Nakard\Laboratory\UserBundle\Service\UserResolverService
    nakard_laboratory_user.registration.form.type:
        class: Nakard\Laboratory\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nakard_laboratory_user_registration }