Nakard\Laboratory\UserBundle\Entity\Users\User:
    type: entity
    table: users
    repositoryClass: Nakard\Laboratory\UserBundle\Entity\Users\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
        length: 255
    discriminatorMap:
        patient: Patient
        assistant: LaboratoryAssistant
        doctor: Doctor
        admin: Administrator
    fields:
        firstName:
            column: first_name
            type: string
            length: 255
        lastName:
            column: last_name
            type: string
            length: 255
        pesel:
            type: string
            length: 255
        registeredAt:
            column: registered_at
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setRegisterDate ]
