Nakard\Laboratory\UserBundle\Entity\Users\Doctor:
    type: entity
    table: users
    repositoryClass: Nakard\Laboratory\UserBundle\Entity\Users\DoctorRepository
    lifecycleCallbacks: {  }
    oneToMany:
        scheduledTests:
            targetEntity: Nakard\Laboratory\TestBundle\Entity\Tests\Test
            mappedBy: scheduler