parameters:
#    nakard_laboratory_application.example.class: Nakard\Laboratory\ApplicationBundle\Example

services:
#    nakard_laboratory_application.example:
#        class: %nakard_laboratory_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    nakard_laboratory_application.user_management:
        class: Nakard\Laboratory\ApplicationBundle\Service\UserManagementService