Nakard\Laboratory\SampleBundle\Entity\Samples\Sample:
    type: entity
    table: samples
    repositoryClass: Nakard\Laboratory\SampleBundle\Entity\Samples\SampleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        admittedAt:
            type: datetime
        type:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
        patient:
            targetEntity: Nakard\Laboratory\UserBundle\Entity\Users\Patient
            inversedBy: samples
    manyToMany:
        tests:
            targetEntity: Nakard\Laboratory\TestBundle\Entity\Tests\Test
            mappedBy: samples
