Nakard\Laboratory\SampleBundle\Entity\Samples\Sample:
    type: entity
    table: samples
    repositoryClass: Nakard\Laboratory\SampleBundle\Entity\Samples\SampleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        admittedAt:
            type: datetime
    lifecycleCallbacks: {  }
    manyToOne:
        patient:
            targetEntity: Nakard\Laboratory\UserBundle\Entity\Users\Patient
            inversedBy: samples
        sampleType:
            targetEntity: Nakard\Laboratory\SampleBundle\Entity\Samples\SampleType
            inversedBy: samples
    oneToMany:
        tests:
            targetEntity: Nakard\Laboratory\TestBundle\Entity\Tests\Test
            mappedBy: sample
