Nakard\Laboratory\UserBundle\Entity\Users\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username, email]
            message: "This username and email combination is already registered"
            repositoryMethod: checkUniqueLoginMailCombination
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [pesel]
            message: "This PESEL number is already registered"
            repositoryMethod: checkUniquePesel
    getters:
        validPesel:
            - 'True': { message: "PESEL is not valid"}
    properties:
        firstName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
            - Regex:
                pattern: "/\d/"
                match:   false
                message: Your name cannot contain a number
        lastName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
            - Regex:
                pattern: "/\d/"
                match:   false
                message: Your surname cannot contain a number
        username:
            - NotBlank: ~
            - Length:
                min: 5
                max: 255
        plainPassword:
            - NotBlank: ~
            - Length:
                min: 8
                max: 255
        email:
            - NotBlank: ~
            - Email:
                strict: true
                message: The email "{{ value }}" is not a valid email
                checkMX: true
        pesel:
            - NotBlank: ~
            - Length:
                min: 11
                max: 11
        registeredAt:
            - DateTime: ~
        type:
            - Choice: { callback: getTypes }