<?php

namespace Nakard\Laboratory\ApplicationBundle\Entity\Tests;

use Doctrine\ORM\EntityRepository;

/**
 * SampleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SampleRepository extends EntityRepository
{
}
