Nakard\Laboratory\ApplicationBundle\Entity\Users\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [login, email]
            message: "This login and email combination is already registered"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: pesel
            message: "This PESEL number is already registered"
    getters:
        validPesel:
            - 'True': { message: "PESEL is not valid"}
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
            - Regex:
                pattern: "/\d/"
                match:   false
                message: Your name cannot contain a number
        surname:
            - NotBlank: ~
            - Length:
                min: 2
                max: 255
            - Regex:
                pattern: "/\d/"
                match:   false
                message: Your surname cannot contain a number
        login:
            - NotBlank: ~
            - Length:
                min: 5
                max: 255
        password:
            - NotBlank: ~
            - Length:
                min: 8
                max: 255
        email:
            - NotBlank: ~
            - Email:
                strict: true
                message: The email "{{ value }}" is not a valid email
                checkMX: true
        pesel:
            - NotBlank: ~
            - Length:
                min: 11
                max: 11
        registerDate:
            - DateTime: ~
        type:
            - Choice: { callback: getTypes }