parameters:
#    nakard_laboratory_test.example.class: Nakard\Laboratory\TestBundle\Example

services:
#    nakard_laboratory_test.example:
#        class: %nakard_laboratory_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
