parameters:
#    nakard_laboratory_test.example.class: Nakard\Laboratory\TestBundle\Example
    nakard_laboratory_test.mosquitto.class: Mosquitto\Client
    nakard_laboratory_test.mosquitto.broker: localhost
    nakard_laboratory_test.mosquitto.port: 1883
    nakard_laboratory_test.mosquitto.client.id: laboratory
    nakard_laboratory_test.redis.class: Predis\Client
    nakard_laboratory_test.redis.uri: tcp://127.0.0.1:6379


services:
#    nakard_laboratory_test.example:
#        class: %nakard_laboratory_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    nakard_laboratory_test.mosquitto.subscriber:
        class: '%nakard_laboratory_test.mosquitto.class%'
        arguments: ['%nakard_laboratory_test.mosquitto.client.id%']
        calls:
            - [connect, ['%nakard_laboratory_test.mosquitto.broker%', '%nakard_laboratory_test.mosquitto.port%', 60]]
    nakard_laboratory_test.redis:
        class: '%nakard_laboratory_test.redis.class%'
        arguments: [%nakard_laboratory_test.redis.uri%]